AllCops:
  Exclude:
    - 'bin/*'
    - 'db'
    - 'db/**/*'
    - 'config/**/*'
    - 'fixtures/*'
    - 'spec/**/*'
    - 'lib/**/*'
    - 'node_modules/**/**/**/*'
    - 'Rakefile'

Style/Documentation:
  Enabled: false

# Metrics/BlockLength:
#   Exclude:
#     - 'spec/**/*'
#     - 'spec/*'
